s3:
  bucket_name: ${oc.env:S3_BUCKET_NAME}

fred:
  api_key: ${oc.env:FRED_API_KEY}
  base_url: https://api.stlouisfed.org/fred
  timeout_seconds: 20.0
  max_retries: 3
  backoff_seconds: 0.5
  jitter_seconds: 0.2
  observation_start: 1990-01-01
  observation_end:
  sort_order: asc
  limit:
  run_date:
  data_quality:
    max_null_ratio_per_series: 0.2
    enforce_monotonic_dates: true
    enforce_unique_series_date: true
    enforce_numeric_parse: true
    enforce_valid_dates: true
  series_ids:
    # ----- inflation
    - CPIAUCSL
    - CPILFESL
    - PCEPI
    - PCEPILFE

    # ----- labor
    - UNRATE
    - PAYEMS
    - CIVPART
    - ICSA

    # ----- growth
    - GDPC1

    # ----- rates / liquidity
    - FEDFUNDS
    - DFF
    - DGS10
    - DGS2
    - T10Y2Y
